- name: Install postgres items
  package:
    name: '{{ item }}'
    state: installed
  with_items:
    - postgresql
    - postgresql-plpython
    - postgresql-server
    - postgresql-contrib
    - postgresql-devel

- name: Initialize postgres if necessary
  command: /usr/bin/postgresql-setup initdb
           creates=/var/lib/pgsql/data/postgresql.conf

- name: Set postgresql-server to run on boot
  service: 
    name: postgresql 
    enabled: yes
  ignore_errors: true

