# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin:$HOME
export LC_COLLATE=C 
export LC_TIME="en_DK.utf8"
export LC_DATE="en_DK.utf8"
export PATH
