# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
export LC_COLLATE=C
export LC_LANG="en_GB.utf8"
export EDIT='/usr/bin/emacs'
export EDITOR='/usr/bin/emacs'
export VISUAL='/usr/bin/emacs'
export LESS=-MM
export MORE="-c"

export CVS_RSH=/usr/bin/ssh
export RSYNC_RSH=/usr/bin/ssh
export PYTHONSTARTUP=~/.pythonrc

# If running interactively, then:
export HISTSIZE=4096
export HISTCONTROL=ignoredups
HISTFILESIZE=1048576

#LAST_HISTORY_WRITE=$SECONDS
#function prompt_command {
#    if [ $(($SECONDS - $LAST_HISTORY_WRITE)) -gt 60 ]; then
#        history -a && history -c && history -r
#        LAST_HISTORY_WRITE=$SECONDS
#    fi
#}

#PROMPT_COMMAND="${PROMPT_COMMAND:-:} ; prompt_command"


function fwho()
{
  local name=$1
  whois $name@geektools.com
}


alias ftp="ftp -i"
alias ls='ls -F --time-style=long-iso'
alias sshadd='ssh-add ~/.ssh/id_fedora_rsa ~/.ssh/id_redhat_rsa ~/.ssh/id_rsa ~/.ssh/id_github_rsa'
alias more='less'
alias mv='mv -iv'
alias cp='cp -iv'
alias rm='rm -iv'
alias sane='stty sane; stty erase "^H" kill "^U" intr "^C"'
alias startx='startx >& ~/Logfiles/startx.out'
alias unsetenv=unset
alias ipsort="sort -t\. -n -k1,1 -k2,2 -k3,3 -k4,4"
alias ipy="ipython -pylab"
alias cleaner="find . -type f -print | grep \~$ | xargs \rm -v"
alias capit="python -c 'import sys; map(lambda x: sys.stdout.write(x.capitalize()), sys.stdin)'"
alias fkinit="kinit -f smooge@FEDORAPROJECT.ORG"
alias clean_space='for f in *\ *; do mv "$f" "${f// /_}"; done'

#export PROMPT_COMMAND='[ "$TERM" == "screen" ] && echo -n -e "\033k\033"'

#xinput disable "SynPS/2 Synaptics TouchPad"

if [ -f /etc/bash_completion.d/git ]; then
   source /etc/bash_completion.d/git 
   if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
      source /usr/share/git-core/contrib/completion/git-prompt.sh
      export PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
   fi
fi

function genpasswd () {
    local RPASSWD=$(dd if=/dev/urandom bs=$1 count=1 2> /dev/null | base64 -w0)
    if [[ $2 = "-n" ]]; then
        echo $RPASSWD | tr -cd "[[:alnum:]]"
    else
        echo $RPASSWD
    fi
}




###
### EOF
###
