## Add in packages needed for mail server
- name: Install the postfix related packages
  package:
    name:
      - postfix
  when: is_external_smtpd
  tags:
      - postfix

## Use the linux-system-roles.postfix to set the rest of the items.
- include_role:
    name: linux-system-roles.postfix
  tags:
      - postfix
