---
ansible_user: root
ansible_python_interpreter: /usr/libexec/platform-python
hostname: "alma8-ws"
domain:   "int.smoogespace.com"
has_ipv4: yes
has_ipv6: yes

network_connections:
  - name: eth0
    state: up
    type: ethernet
    autoconnect: yes
    ip:
      address:
      - "192.168.1.140/24"
      gateway4: "192.168.1.1"
      dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "2001:4860:4860::8888"
      dns_search:
      - int.smoogespace.com
      - smoogespace.com
      auto6: yes
    mac: "00:15:5d:01:0d:02"
