# Default variables for all systems to be configured by playbooks

root_ssh_keys:
        - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP0LzhUTVbwHhX/CVqpVfmhMFJknoUZ/D/L1u4Pot+d0bxVK5bF2NNJzal48wf1N2jv5TpuHLLCzi5eNyOPpz7Y= smooge@smoogen-laptop.localdomain

base_rpm_pkgs: sudo,dnf,gawk,make,wget,tar,bzip2,gzip,python3,unzip,tmux,yum-utils,postfix,bind-utils
base_epel8_pkgs:
base_epel9_pkgs: 
base_fc_pkgs:

admins_list:
   - login_name: ssmoogen
     full_name: Stephen Smoogen
     sudo_right: true
     ssh_pub_key:
        - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP0LzhUTVbwHhX/CVqpVfmhMFJknoUZ/D/L1u4Pot+d0bxVK5bF2NNJzal48wf1N2jv5TpuHLLCzi5eNyOPpz7Y= smooge@smoogen-laptop.localdomain

## defaults which are overridden by other configs
is_external_smtpd: false
has_procmail: false
has_httpd: false

change_sshd: false
alt_sshd: 9022
