---

- name: Create the User Smooge
  user:
    name: smooge
    comment: Stephen Smoogen
    shell: /bin/bash
    uid: 1000
    gid: 1000
    home: /home/smooge
    groups: wheel
    generate_ssh_key: no
    passwd: $6$mzYXXCdnVCr2glZa$KWehpNyu7CBiwz5uJCysv/0Ka3aAiKoOP9Nxa2tdFHvgtWQ93N9JqR0ToMv7ZmtrxhUsMZ8seDTDKGblgq67X1

- name: Create SSH directory
  file:
    path: "/home/smooge/.ssh/"
    state: directory
    mode: 0700

- name: Create bin directory
  file:
    path: "/home/smooge/bin/"
    state: directory
    mode: 0700


- name: Copy over default config files
  copy:
    src: {{ item.src }}
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'ssh_authorized_keys', dest: '/home/smooge/.ssh/authorized_keys' }
    - { src: 'ssh_config', dest: '/home/smooge/.ssh/config' }
    - { src: 'bash_profile', dest: '/home/smooge/.bash_profile' }
    - { src: 'bashrc', dest: '/home/smooge/.bashrc' }
    - { src: 'emacs', dest: '/home/smooge/.emacs' }
    - { src: 'screenrc', dest: '/home/smooge/.screenrc' }
    - { src: 'gitconfig', dest: '/home/smooge/.gitconfig' }

--
