---
hostname: "xenadu"
domain:   "int.smoogespace.com"
has_ipv4: yes
has_ipv6: yes

## Set up the Network address for the system
network_connections:
  - name: eth0
    state: up
    type: ethernet
    autoconnect: yes
    ip:
      address:
      - "192.168.1.150/24"
      gateway4: "192.168.1.1"
      dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "2001:4860:4860::8888"
      dns_search:
      - int.smoogespace.com
      - smoogespace.com
      auto6: yes
    mac: "00:15:5d:01:0d:0a"

firewall:
  - service: https
    zone: 'public'
    state: enabled
  - service: ssh
    zone: 'public'
    state: enabled
  - service: http
    zone: 'public'
    state: enabled
  - service: smtp
    zone: 'public'
    state: enabled
  - service: smtps
    zone: 'public'
    state: enabled
