---
hostname: "xenadu"
domain:   "int.smoogespace.com"
has_ipv4: yes
eno1_ipv4: 192.168.1.150
eno1_ipv4_nm: 24
eno1_ipv4_gw: 192.168.1.1

has_ipv6: yes

ipv4_dns1: "8.8.8.8"
ipv4_dns2: "8.8.4.4"
ivp6_dns1: "2001:4860:4860::8888"

mac0: f8:b1:56:be:ed:32

network_connections:
  - name: eno1
    state: up
    type: ethernet
    autoconnect: yes
    ip:
      address:
      - "{{ eno1_ipv4 }}/{{ eno1_ipv4_nm }}"
      gateway4: "{{ eno1_ipv4_gw }}"
      dns:
      - "{{ ipv4_dns1 }}"
      - "{{ ipv4_dns2 }}"
      - "{{ ipv6_dns1 }}"
      dns_search:
      - int.smoogespace.com
      - smoogespace.com
      auto6: yes
    mac: "{{ mac0 }}"
