# A rolebook to cover installation of a mock builder.
# For the RHEL certificates to work it assumes that you have a system
# configured to use RHEL or a local mirror setup.
# 

# FIXME: this will fail if epel-packages is not installed
- name: == Install Initial packages
  yum:
    name: "{{ pkgs }}"
    state: latest

