---
hostname: "linode00"
domain: "smoogespace.com"

is_external_smtpd: true
has_procmail: true
has_httpd: true

## Items for linux-system-roles.networking
network_connections:
  - name: eth0
    state: up
    type: ethernet
    autoconnect: true
    ip:
      address:
      - "45.33.127.117/24"
      gateway4: "45.33.127.1"
      dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "2001:4860:4860::8888"
      dns_search:
      - smoogespace.com
      auto6: true
    mac: "f2:3c:91:f3:43:ab"

## Setup the Postfix config for the system using
## linux-system-roles.postfix
# Backup multiple times with timestamp
postfix_conf:
  myhostname: linode00.smoogespace.com

## Set up sshd using linux-system-roles.sshd
change_sshd: true

sshd_backup: true
sshd_config_owner: root
sshd_config_group: root
sshd_config_mode: 0600
sshd:
  ListenAddress:
    - 0.0.0.0
    - '::'
  Port: 9022
  Banner: /etc/issue.banner

# Items for Linux firewall which we need before SSH
firewall:
  - service: https
    zone: 'public'
    state: enabled
  - service: ssh
    zone: 'public'
    state: enabled
  - service: http
    zone: 'public'
    state: enabled
  - port: '9022/tcp'
    zone: 'public'
    state: enabled
  - service: smtp
    zone: 'public'
    state: enabled
  - service: smtps
    zone: 'public'
    state: enabled

# Items for time sync
timesync_ntp_servers:
  - hostname: 0.cloudlinux.pool.ntp.org
    iburst: yes
  - hostname: 1.cloudlinux.pool.ntp.org
    iburst: yes
  - hostname: 2.cloudlinux.pool.ntp.org
    iburst: yes
timezone: UTC
