# A rolebook to cover installation of a 'local' mirror.

# Ensure server has correct packages needed
- name: Install the OS base packages
  yum:
    name: "{{ mirror_pkgs }}"
    state: latest

# Set up the mirror directory tree.
- name: == Set up all vault directory trees
  block:
    - name: === Set up the mirror top directory
      file: state=directory path={{ server_homedir }} owner=root group=root mode=0775 setype=httpd_sys_content_t seuser=system_u
    - name: === Set up the CentOS directory
      file: state=directory path={{ server_homedir }}/centos-vault/ owner=root group=root mode=0775 setype=httpd_sys_content_t seuser=system_u
    - name: === Set up the EPEL directory
      file: state=directory path={{ server_homedir }}/epel-vault/ owner=root group=root mode=0775 setype=httpd_sys_content_t seuser=system_u

- name: == Setup the httpd server configs
  template: src=mirror-httpd.conf.j2 dest=/etc/httpd/conf.d/mirror-httpd.conf mode=0644

- name: == Setup the httpd systemctl
  service:
    name: httpd
    state: started

- include_role:
    name: linux-system-roles.firewall
  tags:
    - httpd
    - firewall

