---
# Common Tasks for a CentOS-7 system

# Make sure we have epel
- name: Install epel-release
  package:
    name: epel-release
    state: installed

# Packages we should have
- name: Install core packages
  package:
    name: '{{ item }}'
    state: installed
  with_items:
    - bc
    - bind-utils
    - chrony
    - elinks
    - emacs-nox
    - hunspell-en
    - hunspell-en-GB
    - hunspell-en-US
    - lftp
    - lshw
    - lsof
    - mailx
    - man-pages
    - man-pages-overrides
    - mlocate
    - mtr
    - net-tools
    - pinfo
    - psacct
    - screen
    - sudo
    - sysstat
    - task
    - tcpdump
    - time
    - traceroute
    - vim-enhanced
    - wget
    - words
    - yum-utils
    
