---
# Common Tasks for a CentOS-7 system

# Make sure we have epel
- name: Install epel-release
  package:
    name: epel-release
    state: latest

# Packages we should have
- name: Install core packages
  package:
    name: '{{ item }}'
    state: installed
  with_items:
    - screen
    - sudo
    - vim-enhanced
    - git
    - emacs-nox
    - task
    - yum-utils

- name: Install devel packages
  package:
    name: '{{ item }}'
    state: installed
  with_items:
    - emacs-rpm-spec-mode
    - emacs-git
    - fedpkg
    - fedora-easy-karma
    - fedora-cert
    - fedora-review
    - fedora-packager
    - centos-packager
  when: devel_env

