---
- name: Install system specific packages
  package:
    name: '{{ item }}'
    state: installed
  with_items:
    - gnuplot
    - python-flask
    - python-pandas
    - python-pygeoip.noarch
    - python2-fedora-flask.noarch
    - python-virtualenv.noarch
    - python-ipython-console.noarch
