##
## These servers are fairly unloaded for US users. EU users should find
## a mirror in the EU.
centos_vault_mirror: archive.kernel.org
epel_vault_mirror: dl.fedoraproject.org
alma_upstream_mirror: iad.mirror.rackspace.com

## Home directory we want to put the packages in and httpd will serve from.
server_homedir: /srv/mirrors

mirror_pkgs: dnf-utils, python3-policycoreutils, httpd, createrepo_c
