---
- name: Setup initial systems
  hosts: int_smoogespace,ext_smoogespace
  become: false
  gather_facts: true
  roles:
    - common
    - users
    - linux-system-roles.network
    - linux-system-roles.timesync
    - sshd
