---

# This is a simple playbook to set up a system to develop programs for
# Champlain College SDEV-435 on a CentOS-7 system
#

- name: Setup System
  hosts: sdev435
  user: root
  gather_facts: True

  roles:
    - common
    - add_smooge
    - sdev435  


## End of file
