---

# This is a simple playbook to set up a system to develop programs for
# Champlain College SDEV-435 on a CentOS-7 system
#

- name: Setup System
  hosts: smoogespace_new
  user: root
  gather_facts: True

  roles:
    - common


## End of file
